### PR TITLE
add types reference in package.json of tweek-client

### LINKED ISSUE #51: no declaration found for tweek-client
Although the package is written in typescript, there is no decleration file exported from the library, so it can't be consumed in Typescript (unless I add my own typings..)
```
Could not find a declaration file for module 'tweek-client'. '/.../node_modules/tweek-client/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/tweek-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'tweek-client';`
```

Solution:
Add `"types": "./dist/index.d.ts"` to `package.json`

### PR DESCRIPTION
**Pull request by oreporan**
closes #51

### CODE REVIEW

**Comment by oreporan** [comment]
@Yshayy - any idea why this fails?

**Comment by nataly87s** [comment]
@oreporan please merge from master and try again, it should fix the issue

**Comment by oreporan** [comment]
@nataly87s can this be merged ?

**Comment by nataly87s** [comment]
Yeah, but can you please do the same change in `tweek-local-cache`?
Thanks ☺️

**Comment by oreporan** [comment]
btw - there is no link from npm to the github repo, makes it a bit harder to find, especially since its a lerna repo....

**Comment by nataly87s** [comment]
I'll add the url when I bumb the version tomorrow morning

**Pull request merged**
